__rust_base: &rust_base
  language: rust
  rust:
    - 'stable'


stages:
  - compile
  - lint
  - test
  - deploy


matrix:
  include:

    # COMPILE

    - name: 'compile'
      stage: compile
      <<: *rust_base
      script:
        - cargo build --verbose

    # LINT
    - name: 'lint'
      stage: lint
      <<: *rust_base
      before_script:
        - rustup component add clippy
      script:
        - cargo clippy --all-targets --all-features -- -D warnings

    # TEST
    - name: 'test'
      stage: test
      <<: *rust_base
      script:
        - cargo test --verbose .
